logging.level.org.springframework.web: DEBUG

app:
  conversion-rate-store.size-in-days: 93

ecb:
  client:
    connection-timeout: 5000
    max-retries: 5
  manager:
    crawl-cron: "*/10 * * * * *"
  parser:
    currency-attribute-name: "currency"
    default-from-currency-code: "EURO"
    rate-attribute-name: "rate"
    time-attribute-name: "time"